config/routes.rb
Rails.application.routes.draw do

  root :to => 'home#index'

  get '/' => 'home#index', as: "home"

  resources :publications
  get 'anuncio/ver/:id' => 'publications#show', as: "anuncio"

  get 'anuncios/tipo/:type' => 'dashboard#type', as: "type"
  get 'dashboard/:id' => 'dashboard#index', as: "dashboard"
  get 'directorio/ver/:id' => 'dashboard#index', as: "directorio"

  get 'search/' => 'search#index', as: "search"

  resources :images

  resources :ubications

  resources :features

  devise_for :users, :controllers => { registrations: 'registrations' }

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
 
  def index
  	@ubication = Ubication.where('city LIKE ?', "%#{params[:q]}%")
  end

end

app/views/search/index.html.erb
 <% content_for :title, "Todos los resultados de la busqueda encontrados" %>

 <% if user_signed_in? && current_user.updated == 0 %>
    <nav id="update">
      <ul>
        <a class="message"><li>Favor de completar tu perfil al 100%, para lograr mejores resultados en la plataforma: </li></a>
        <a href="/users/edit" class="link">
          <li> Actualizar perfil</li>
        </a>
      </ul>
    </nav>
<% end %>

<% contador = 0 %>

<% @ubication.each do |ubicat| %>
	  <% @publi = Publication.where("id = ? AND type_add = ? AND type_property = ?",ubicat.publication_id , params[:type_add], params[:type]) %>
	<% @publi.each do |publicat| %>
	  <% contador = contador + 1 %>
	 <% end -%>
<% end -%>

<header id="head-dashboard">
  <div class="profile">
    <h1>
      Todos los inmuebles en <%= params[:type]%>
    </h1>
    <h2>
      <%= contador%> inmuebles en <%= params[:type]%>
    </h2>
  </div>
  <form action="/search" class="cd-form floating-labels search" method="get">

    <h1>Nueva Buesqueda</h1>
			<p class="cd-select icon">
				<select name="type" id="" class="down opt-select">
					<option value="Venta">Venta</option>
					<option value="Renta">Renta</option>
				</select>
			</p>
			<p class="cd-select icon">
				<select name="type_add" id="" class="down opt-select">
					<option value="Casa">Casa</option>
					<option value="Departamento">Departamento</option>
					<option value="Oficina">Oficina</option>
					<option value="Local">Local</option>
					<option value="Bodega">Bodega</option>
					<option value="Terreno">Terreno</option>
				</select>
			</p>
			<div class="input">
				<input type="text" name='q' <%= @q %> placeholder="Donde ej. Durango, Mazatlán, Nayarit">
			</div>
			<div class="go-search">
				<input type="submit" value="Buscar">
			</div>
		</form>
</header> 


<main id="cont-dashboard">
  <section class="cont">
  <% if contador == 0 %>
      <h1>Lo sentimos aún no hay resultados de tu búsqueda. Intentalo en otro momento.</h1>
      <% if user_signed_in? %>
        <%= link_to new_publication_path, :class => 'link-new-pub' do%>
          Agregar anuncio
        <%end%>
      <% else %>
        <%= link_to new_user_registration_path, :class => 'link-new-pub' do%>
          Agregar anuncio
        <%end%>
      <% end -%>
    <% end %>
  <% @ubication.each do |ubications| %>
	  <% @publications = Publication.where("id = ? AND type_add = ? AND type_property = ?",ubications.publication_id , params[:type_add], params[:type]) %>

  <% @publications.each do |publication| %>
    <%= link_to anuncio_path(publication) do%>  
    <% @avatar = User.where(:id => publication.user_id).first %>
    <% if @avatar %>          
      <article class="properties">
        <% @avatar = User.where(:id => publication.user_id).first %>
        <figure class="avatar"><%= image_tag @avatar.avatar, :alt => "Avatar", :title => "Avatar"%></figure>
        <% @image = Image.where(:publication_id => publication.id).first%>
        <% if @image == nil%>
          <figure class="img-con"><%= image_tag "default-no-image.png", :alt => "Condominio", :title => "Condominio"%></figure>
        <% else %>
          <figure class="img-con"><%= image_tag @image.url, :alt => "Condominio", :title => "Condominio"%></figure>
        <% end -%>
        <% if user_signed_in? && current_user.id == params[:id].to_f %>
          <div class="price">
            <%= link_to publication, :class => "icon-function" do%>
              <span class="ion-android-open"></span>
            <% end -%>
            <%= link_to edit_publication_path(publication), :class => "icon-function" do%>
              <span class="ion-android-create"></span>
            <% end -%>
            <%= link_to publication, method: :delete, data: { confirm: '¿Estás seguro que deseas eliminar el registro?' }, :class => "icon-function" do%>
              <span class="ion-android-delete"></span>
            <% end -%>
          </div>
        <% else %>
          <div class="price">
            $<%= number_with_delimiter(publication.price) %>
          </div>
        <% end -%>
        <div class="content">
          <h1 class="title"><%= publication.title %></h1>
          <ul class="cont-info">
            <% Ubication.where(:publication_id => publication.id).each do |ubication|%>
              <li><span class="ion-location"></span> <%= ubication.town %></li>
            <% end %>
            <%if publication.type_add == "Bodega" || publication.type_add == "Terreno" %>
              <li><span class="ion-ios-home"></span> <%= publication.type_add %></li>
              <li>Dimenciones: <%= publication.size %>m2</li>
            <%else%>
              <li><span class="ion-ios-home"></span> <%= publication.type_add %></li>
              <li><span class="icon-room"></span> <%= publication.rooms %></li>
              <li><span class="icon-bathroom"></span> <%= publication.bathrooms %></li>
            <% end -%>
          </ul>
        </div>
      </article>
    <% end -%>
    <% end -%>
  <% end -%>
 <% end -%>
 </section>
 </main>