config/routes.rb
Rails.application.routes.draw do

  root :to => 'home#index'

  get '/' => 'home#index', as: "home"

  resources :publications
  get 'anuncio/ver/:id' => 'publications#show', as: "anuncio"

  get 'anuncios/tipo/:type' => 'dashboard#type', as: "type"
  get 'dashboard/:id' => 'dashboard#index', as: "dashboard"
  get 'directorio/ver/:id' => 'dashboard#index', as: "directorio"

  get 'search/' => 'search#index', as: "search"

  resources :images

  resources :ubications

  resources :features

  devise_for :users, :controllers => { registrations: 'registrations' }

end

app/models/ubication.rb
class Ubication < ActiveRecord::Base
  belongs_to :publication
end

app/controllers/ubications_controller.rb
class UbicationsController < ApplicationController
  load_and_authorize_resource
  before_action :set_ubication, only: [:show, :edit, :update, :destroy]

  # GET /ubications
  # GET /ubications.json
  def index
    @ubications = Ubication.all
  end

  # GET /ubications/1
  # GET /ubications/1.json
  def show
  end

  # GET /ubications/new
  def new
    @ubication = Ubication.new
  end

  # GET /ubications/1/edit
  def edit
    @images = Image.where(publication_id: params[:id])
  end

  # POST /ubications
  # POST /ubications.json
  def create
    @ubication = Ubication.new(ubication_params)
    @ubication.user_id = current_user.id 
    respond_to do |format|
      if @ubication.save
        format.html { redirect_to :controller => 'images', :action => "new", :id_pub => @ubication.publication_id }
        format.json { render :show, status: :created, location: @ubication }
      else
        format.html { render :new }
        format.json { render json: @ubication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ubications/1
  # PATCH/PUT /ubications/1.json
  def update
    respond_to do |format|
      if @ubication.update(ubication_params)
        @image = Image.find_by(publication_id: @ubication.id)
        format.html {  redirect_to :controller => 'images', :action => "new", :id_pub => @ubication.publication_id}
        format.json { render :show, status: :ok, location: @ubication }
      else
        format.html { render :edit }
        format.json { render json: @ubication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ubications/1
  # DELETE /ubications/1.json
  def destroy
    @ubication.destroy
    respond_to do |format|
      format.html { redirect_to ubications_url, notice: 'Ubication was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ubication
      @ubication = Ubication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ubication_params
      params.require(:ubication).permit(:country, :city, :town, :street, :number_out, :number_in, :colony, :postal, :publication_id, :user_id)
    end
end

app/helpers/ubications_helper.rb
module UbicationsHelper
end

app/views/ubications/_form.html.erb
<% content_for :title, "Paso 2: Agregar ubicación" %>
<div>
<%= form_for(@ubication, :html => {:class => "cd-form floating-labels"}) do |f| %>
  <% if @ubication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ubication.errors.count, "error") %> prohibited this ubication from being saved:</h2>

      <ul>
      <% @ubication.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
    <legend>Paso 2 agrega la ubicación de tu inmueble</legend>
      <div class="icon">
        <%= f.label :country, "País", :class => "cd-label" %>
        <%= f.text_field :country, :class => "ubication", :required => true, autocomplete: "off"  %>
      </div>
      <div class="icon">
        <%= f.label :city, "Ciudad", :class => "cd-label" %>
        <%= f.text_field :city, :class => "ubication", :required => true, autocomplete: "off" %>
      </div>
      <div class="icon">
        <%= f.label :town, "Estado", :class => "cd-label"  %>
        <%= f.text_field :town, :class => "ubication", :required => true, autocomplete: "off" %>
      </div>
      <div class="icon">
        <%= f.label :street, "Calle", :class => "cd-label" %>
        <%= f.text_field :street, :class => "ubication", :required => true, autocomplete: "off" %>
      </div>
      <div class="icon">
        <%= f.label :number_out, "Número exterior", :class => "cd-label" %>
        <%= f.number_field :number_out, :class => "ubication", :required => true, autocomplete: "off" %>
      </div>
      <div class="icon">
        <%= f.label :number_in, "Número interior", :class => "cd-label" %>
        <%= f.number_field :number_in, :class => "ubication", autocomplete: "off" %>
      </div>
      <div class="icon">
        <%= f.label :colony, "Colonia", :class => "cd-label" %>
        <%= f.text_field :colony, :class => "ubication", :required => true, autocomplete: "off" %>
      </div>
      <div class="icon">
        <%= f.label :postal, "Código postal", :class => "cd-label" %>
        <%= f.number_field :postal, :class => "ubication", :required => true, autocomplete: "off" %>
      </div>

        <%= f.hidden_field :publication_id, :value => params[:id_pub] %>
        <%= f.hidden_field :user_id %>

      <div class="actions">
        <%= f.submit :value => "Paso 3"%>
      </div>
    <% end %>
</div>

app/views/ubications/edit.html.erb
<%= render 'form' %>

app/views/ubications/index.html.erb
<!-- <p id="notice"><%= notice %></p>

<h1>Listing Ubications</h1>

<table>
  <thead>
    <tr>
      <th>Country</th>
      <th>City</th>
      <th>Town</th>
      <th>Street</th>
      <th>Number out</th>
      <th>Number in</th>
      <th>Colony</th>
      <th>Postal</th>
      <th>Publication</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ubications.each do |ubication| %>
      <tr>
        <td><%= ubication.country %></td>
        <td><%= ubication.city %></td>
        <td><%= ubication.town %></td>
        <td><%= ubication.street %></td>
        <td><%= ubication.number_out %></td>
        <td><%= ubication.number_in %></td>
        <td><%= ubication.colony %></td>
        <td><%= ubication.postal %></td>
        <td><%= ubication.publication %></td>
        <td><%= link_to 'Show', ubication %></td>
        <td><%= link_to 'Edit', edit_ubication_path(ubication) %></td>
        <td><%= link_to 'Destroy', ubication, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ubication', new_ubication_path %>
 -->

app/views/ubications/new.html.erb
<%= render 'form' %>

app/views/ubications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Country:</strong>
  <%= @ubication.country %>
</p>

<p>
  <strong>City:</strong>
  <%= @ubication.city %>
</p>

<p>
  <strong>Town:</strong>
  <%= @ubication.town %>
</p>

<p>
  <strong>Street:</strong>
  <%= @ubication.street %>
</p>

<p>
  <strong>Number out:</strong>
  <%= @ubication.number_out %>
</p>

<p>
  <strong>Number in:</strong>
  <%= @ubication.number_in %>
</p>

<p>
  <strong>Colony:</strong>
  <%= @ubication.colony %>
</p>

<p>
  <strong>Postal:</strong>
  <%= @ubication.postal %>
</p>

<p>
  <strong>Publication:</strong>
  <%= @ubication.publication %>
</p>

<%= link_to 'Edit', edit_ubication_path(@ubication) %> |
<%= link_to 'Back', ubications_path %>