config/routes.rb
Rails.application.routes.draw do

  root :to => 'home#index'

  get '/' => 'home#index', as: "home"

  resources :publications
  get 'anuncio/ver/:id' => 'publications#show', as: "anuncio"

  get 'anuncios/tipo/:type' => 'dashboard#type', as: "type"
  get 'dashboard/:id' => 'dashboard#index', as: "dashboard"
  get 'directorio/ver/:id' => 'dashboard#index', as: "directorio"

  get 'search/' => 'search#index', as: "search"

  resources :images

  resources :ubications

  resources :features

  devise_for :users, :controllers => { registrations: 'registrations' }

end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :publication

	mount_uploader :url, PhotoUploader

	# FOTOS = File.join Rails.root, 'public', 'photo_store'
	# after_save :guardar_foto

	# def url=(file_data)
	# 	unless file_data.blank?
	# 		@file_data = file_data
	# 		self.url = file_data.original_filename.split('.').last.downcase
	# 	end
	# end

	# def photo_filename
	# 	File.join FOTOS, "#{id}.#{url}"
	# end

	# def photo_path
	# 	"/photo_store/#{id}.#{url}"
	# end

	# private

	# def guardar_foto
	# 	if @file_data
	# 		FileUtils.mkdir_p FOTOS
	# 		File.open(photo_filename, 'wb') do |f|
	# 			f.write(@file_data.read)
	# 		end
	# 		@file_data = nil
	# 	end
	# end  	
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  load_and_authorize_resource
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @images = Image.where(publication_id: params[:id_pub])
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
    @images = Image.where(publication_id: params[:id])
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)
    @image.user_id = current_user.id 
    respond_to do |format|
      if @image.save
        format.html {redirect_to :controller => 'images', :action => "new", :id_pub => @image.publication_id }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to :controller => 'images', :action => "new", :id_pub => @image.publication_id }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to :controller => 'images', :action => "new", :id_pub => @image.publication_id }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:url, :publication_id, :user_id)
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<article class="cont-images">
  <h2>Fotos de tu publicación </h2>
  <% @images.each do |images| %>
    <div class="center-cropped">
          <%= image_tag(images.url)%>
          <%= link_to  images, method: :delete, data: { confirm: '¿Estas Seguro?' }, :class => "delete-image" do %>
            <span class="ion-android-delete"></span>
          <% end -%>
    </div>

  <% end %>
</article>
<div>
<%= form_for(@image, :html => { :multipart => true, :class => "cd-form floating-labels" }) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
      <legend>Paso 3 selecciona las imagenes para tu publicación</legend>
      <h4>Selecciona imagen</h4>
      <div class="file">
        <%= f.file_field :url %>
      </div>

        <%= f.hidden_field :publication_id, :value => params[:id_pub] %>
        <%= f.hidden_field :user_id %>

        <%= f.submit :value => "Agregar imagen", :class => "full-input" %>

      <%= link_to dashboard_path(:controller => "dashboard", :action => "index", :id => current_user.id), :class => 'end-publication' do%>
        Guardar y finalizar
      <% end -%>
<% end -%>
</div>

app/views/images/edit.html.erb
<%= render 'form' %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Images</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Publication</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.url %></td>
        <td><%= image.publication %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<% content_for :title, "Paso 3: Agregar imagenes" %>
<%= render 'form' %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @image.url %>
</p>

<p>
  <strong>Publication:</strong>
  <%= @image.publication %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>